### ISSUE TITLE
Resolve attribute references within attribute values defined in config

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#103]
Substitution attribute references (e.g., `{imagesdir}`) within attribute values in the configuration. Attribute values are assigned to attribute names in the attributes block of the asciidoctor configuration.

Example:

```yaml
asciidoctor:
  attributes:
    imagesdir: images
    iconsdir: {imagesdir}/icons
```

These attributes references have to be resolved by the plugin since they are not resolved when passed to the Asciidoctor API.
