### ISSUE TITLE
Provide a way to remove a previously defined attribute in config

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#123]
Provide a means to remove a built-in attribute in the configuration, but not propagate that attribute as unset on to documents. In other words, provide a way to remove an attribute previously defined as though it was never defined.

The proposed syntax for this is as follows:

```yml
asciidoctor:
  attributes:
    - -idseparator
```

Initially, I though about using this syntax:

```yml
asciidoctor:
  attributes:
    - !idseparator=@
```

However, I'm reserving that syntax for future use in Asciidoctor.
