### ISSUE TITLE
Allow AsciiDoc attributes to be defined on asciidoc config key

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#126]
It's more fitting for AsciiDoc attributes to be defined on the asciidoc config key rather than the asciidoctor config key.

``` yml
asciidoc:
  attributes:
    - idseparator=_
asciidoctor:
  base_dir: :docdir
  # these attributes inherit from the generic attributes and are specific to Asciidoctor
  attributes:
    - icons=font
    - source-highlighter=coderay
```

For backwards compatibility, and to allow attributes specific to a given processor, we can still support both locations. The attributes defined on the asciidoctor key will inherit the attributes that are defined on the asciidoc key.
