### ISSUE TITLE
Per-scope asciidoctor attribute values

### ISSUE THREAD

**Issue by akomakom** [asciidoctor/jekyll-asciidoc#134]
Is it possible to provide different attribute values **per jekyll scope**?

ie:

```yaml
asciidoctor:
  attributes:
     - imagesdir='/images'
defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: "asciidoctor1/subdirectory"
      type: "pages"
    values:
      layout: "custom"
      asciidoctor:
        attributes:
            imagesdir: "/different/path"

```
Which would override the value of **imagesdir** specified in **asciidoctor->attributes** for the given path?  

Alternatively, all scope values could be blindly made available to asciidoctor:

```yaml
defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: "asciidoctor1/subdirectory"
      type: "pages"
    values:
      layout: "custom"
      imagesdir: "/different/path"

```

(just two examples of possible syntax).

At this time I'm finding that the scope concept is entirely disconnected from asciidoctor configuration - there is no way to reference values between them in either direction (being able to reference them would be another way to reduce duplicated configuration)

If there is a way to do any of the above already, please point me in the right direction.
