### ISSUE TITLE
add support for reveal.js (e.g. via asciidoctor-reveal.js)

### ISSUE THREAD

**Issue by tortoise74** [asciidoctor/jekyll-asciidoc#136]
Hi,
   I've been experimenting with adding presentations using reveal.js.
The instructions here:

 http://toddstoffer.github.io/blog/adding-reaveal.js-to-jekyll-academic/

work for markdown but not for asciidoctor (as it uses markdown embedded in the page).

Away from jekyll I found this project:

 https://github.com/asciidoctor/asciidoctor-reveal.js/

which renders the asciidoc into html in the format required by reveal.js

What would be needed to make jekyll-asciidoc do render using asciidoctor-reveal.js (or similar) for posts using a special slide layout?

As a workaround I can run asciidoctor-reveal.js offline and copy the html into my source before running jekyll but this is not ideal.

Regards,

Bruce.

**Comment by mojavelinux** [comment]
Yes, it's possible for different pages to use different backends (i.e., converters).

Here's how you set it up. First, add the asciidoctor-revealjs gem to your Gemfile:

```ruby
source 'https://rubygems.org'

gem 'jekyll', '3.3.0'

group :jekyll_plugins do
  gem 'jekyll-asciidoc'
  gem 'asciidoctor-revealjs'
end
```

Next, setup some configuration in the Jekyll configuration file:

```yaml
gems:
  - jekyll-asciidoc
  - asciidoctor-revealjs
asciidoc:
  processor: asciidoctor
asciidoctor:
  safe: safe
  attributes:
    revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0
```

If you have a local copy of revealjs, you can point to that. It's best to abstract this information from the AsciiDoc source.

Finally, create your slides in the file slides.adoc and configure that file to use the revealjs converter:

```
= Title Slide
:backend: revealjs
:page-layout: false

== First Slide

* Foo
* Bar
* World

== Second Slide

Content

=== Vertical Slide

This is a vertical slide.

== Another Horizontal Slide

...that's all she wrote!
```

You should now be able to view the slides by running `jekyll serve` and navigating to http://localhost:4000/slides.html.
