### ISSUE TITLE
asciidoctor diagram not working as in the README

### ISSUE THREAD

**Issue by a4z** [asciidoctor/jekyll-asciidoc#155]
I try to follow the readme, this is what I have

Gemfile
```
source "https://rubygems.org"
ruby RUBY_VERSION

gem "jekyll", "3.4.3"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem 'asciidoctor-diagram'
   gem 'jekyll-asciidoc' ,  '>= 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

_config.yml
```
title: Your awesome title
email: your-email@domain.com
description: and this is what it does
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

theme: minima

gems:
  - asciidoctor-diagram
  - jekyll-asciidoc

asciidoc:
  ext: adoc

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images

exclude:
  - Gemfile
  - Gemfile.lock
```

sample.adoc in the root
```
= Sample Page
:uri-asciidoctor: http://asciidoctor.org
imagesdir: images

This is a sample page composed in AsciiDoc.
Jekyll converts it to HTML using {uri-asciidoctor}[Asciidoctor].

[source,ruby]
puts "Hello, World!"

== some diagram

[plantuml, diagram-classes, png]     
----
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
----

```

I know that this setup is pretty incomplete, but should I not at least get some diagram generated ?

ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by a4z** [comment]
found some help in #41, now generation works

**Comment by mojavelinux** [comment]
Is there something we could add to the README to help other users get it setup?

**Comment by a4z** [comment]
still experimenting, this morning, start from scratch with an empty initialized folder,  but I think the relevant change in the _config.yml was that one
```
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
    imagesoutdir: images
```
so it seems adding the `imagesoutdir: images` is what is missing in the reamde
because I think the rest is equal to what I had yesterday, 

now I have at least the images generated, yesterday they have not even be generated.

I still need to do some thing so that the images are also displayed, adopt the images dir, and set them up
images are generated but not moved to the _site directory, so it seems there is still something to tweek.
So I have no final recipe how to lower the entry barrier, if I find out the details I will make a pull request
