### ISSUE TITLE
Using emoji instead of font-awesome

### ISSUE THREAD

**Issue by dareenzo** [asciidoctor/jekyll-asciidoc#174]
Hello,

first of all, thanks for this lib. It's quite handy.

I want to know if there's a way an official to use emoji as admonitions?! So far only font-awesome and images seem to be supported.

As of now, I'm hacking around and pretending that I want to use font-awesome but then replacing the content with an emoji as shown in the snippet below. Is this something you'd recommend?

Thanks

```css
span.icon>.fa {
  cursor: default;
}

.admonitionblock td.icon {
  text-align: center;
  width: 80px;
}
.admonitionblock td.icon [class^="fa icon-"] {
  font-size: 1.5em;
  text-shadow: 1px 1px 2px rgba(0,0,0,.5);
  cursor: default;
}
.admonitionblock td.icon .icon-note:before {
  content: "\f05a";
  content: "📎";
  color: #19407c;
}
.admonitionblock td.icon .icon-tip:before {
  content: "\f0eb";
  content: "💡";
  text-shadow: 1px 1px 2px rgba(155,155,0,.8);
  color: #111;
}
.admonitionblock td.icon .icon-warning:before {
  content: "\f071";
  content: "⚠";
  color: #bf6900;
}
.admonitionblock td.icon .icon-caution:before {
  content: "\f06d";
  content: "🔥";
  color: #bf3400;
}
.admonitionblock td.icon .icon-important:before {
  content: "\f06a";
  content: "❗";
  color: #bf0000;
}
```
