### ISSUE TITLE
Layout isn't used correctly in some cases

### ISSUE THREAD

**Issue by henri-tremblay** [asciidoctor/jekyll-asciidoc#187]
I've migrated from 1.0.1 to higher. 1.1.2 doesn't work and 1.1.1 has another issue.

I use jekyll 3.7.4. The original source code for this issue is [here](https://github.com/ehcache/ehcache.org-site).

 So `_config.xml` looks like this:

```yml
plugins:
  - jekyll-asciidoc
  - jekyll-sitemap


asciidoctor:
  # We need safe since we go fetch code examples in directories lower than where the adoc file is
  safe: 0
  attributes:
    - hardbreaks!
    - source-highlighter=prettify
    - pygments-css=style
    - icons=font
    - sourcedir36=_eh36
    - imagesdir=images
    - sectanchors
    - idprefix
    - idseparator=-

defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: "documentation/3.6"
      type: "pages"
    values:
      layout: "docs35_page"
```

So I would expect "docs35_page" to be selected when in the "documentaion/3.6" directory. But this is not happening.

The front matter  is each page is empty and is following by an include.

```
---
---
= Cache Event Listeners
ifndef::sourcedir36[]
include::common.adoc[]
endif::sourcedir36[]
```

The `common.adoc` file seems to contain nothing related.

```
---
---
ifndef::sourcedir36[]
:notBuildingForSite: true
ifdef::basebackend-html[:outfilesuffix: .html]
:source-highlighter: coderay
:stylesdir: css
:stylesheet: ehcache.css
:linkcss:
:icons: font
:iconfont-remote!:
:iconfont-name: font-awesome.min
:sourcedir36: ../../../../../
:imagesdir: images
:sectanchors:
:idprefix:
:idseparator: -
endif::sourcedir36[]
```

I have no clue why this is happening.
