### ISSUE TITLE
Background mismatch in code blocks with pygments, using default theme/style

### ISSUE THREAD

**Issue by ydirson** [asciidoctor/jekyll-asciidoc#229]
I'm using jekyll 3.8.6, minima 2.5.1, pygments.rb 1.2.1, configured as follows:

```yaml
asciidoctor:
  attributes:
    source-highlighter: pygments
    pygments-css: style
```

On one hand the code block is wrapped by `<pre class="pygments highlight" style="background: #f8f8f8;">`, OTOH main.css sets `code { background-color: #eef; }`.  This gives a pretty ugly result, whereas the default markdown styling with Rouge manages to be consistent here.

This main.css rule also applies to inline code not going through pygments, and it makes sense for both cases to be consistent.  That seems to leave us with tuning the pygments style to match.

Using liquid `{% highlight python %}` in a passthough block gives the expected result, though.
