### ISSUE TITLE
imagesdir does not seem to affect asciidoctor-diagram and relative generation info missing ?

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/jekyll-asciidoc#234]
readme states if you do this:

```
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
```

asciidoctor-diagram generates into /images - that does not seem to be the case; with this they show in `_site/posts/*.png`.

Which actually is fine - but then generation of asciidoc posts does not work when rendered as a list since now the relative link does not work.

Is there a way as mentioned in #178 to control the image location for asciidoctor diagrams separate from other images + have the generation of docs use absolute or proper relative paths ?
