### ISSUE TITLE
Cannot generate SVG with PlantUML (while PNG has no problem)

### ISSUE THREAD

**Issue by aiotter** [asciidoctor/jekyll-asciidoc#253]
I have this thing in my post:
```adoc
[plantuml, format=svg, opts="inline"]
----
legend
Root
|_ node
end legend
----
```
And got this error:
```
asciidoctor: WARNING: <stdin>: SVG does not exist or cannot be read: /img/diag-4655cb7495c60605f9ca5c24711cf5a4.svg
```
The resulting HTML has no image.
This problem only occurs when you use `format=svg` option. Without that option you have no problem with the resulting HTML with PNG image.

Following is a part of my config.yml:
```yml
keep_files:
  - img
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - imagesdir=/img
```

P.S. Thank you for creating jekyll-asciidoc! This plugin made me move from Hugo to Jekyll. There were lots of problems using asciidoc with Hugo, but thanks to jekyll-asciidoc, I have had no problem except for the one above.
