### ISSUE TITLE
Setting the font admonition icons feature is not correct in the README

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/jekyll-asciidoc#268]
I just stepped through the README to get the font icons for my admonition blocks working. The good news is that the main instructions worked really well except for one part:

```
or in the site configuration:

asciidoctor:
  attributes:
  - icons=font
  ...
```

The block above caused a parsing error at the `- icons=font` position.

```
23:55:18: [jekyll]: jekyll 3.8.5 | Error: (_config.yml): did not find expected key while parsing a block mapping at line 43 column 5
```

To correct the issue I set the following config in my `_config.yml` file which fixed the issue

```
asciidoctor:
  attributes:
    imagesdir: /assets/images
    icons: font
```

**Comment by mojavelinux** [comment]
It's not that the recommendation is incorrect. It's that there are two different syntax styles you can use when defining attributes, and those styles cannot be mixed (per YAML rules).

The attributes can either be defined using array entries:

```
asciidoctor:
  attributes:
  - imagesdir=/assets/images
  - icons=font
```

or they can be defined as map entries:

```
asciidoctor:
  attributes:
    imagesdir: /assets/images
    icons: font
```

But not as a mix of both:

```
asciidoctor:
  attributes:
    imagesdir: /assets/images
  - icons=font
```

This is explained in this section: https://github.com/asciidoctor/jekyll-asciidoc#asciidoctor

If you feel this needs to be pointed out, please propose a docs change.
