### ISSUE TITLE
asciidoctor-diagram fails to find dot.exe

### ISSUE THREAD

**Issue by BerkhanEminsoy** [asciidoctor/jekyll-asciidoc#273]
Although I'm not sure if this is right place to post this but as I've summarized in the title, after following [the instructions](https://github.com/asciidoctor/jekyll-asciidoc#enabling-asciidoctor-diagram) to enable the asciidoctor-diagram in .adoc files, the extension fails to find dot.exe, throwing the errors below;

```
asciidoctor: ERROR: 2017-05-20-diagram-in-a-post.adoc: line 8: Failed to generate image: Could not find the 'dot' executable in PATH; add it to the PATH or specify its location using the 'graphvizdot' document attribute
asciidoctor: ERROR: 2017-05-20-diagram-in-a-post.adoc: line 18: Failed to generate image: no implicit conversion of nil into String
asciidoctor: ERROR: ascii-sampleDiagram.adoc: line 7: Failed to generate image: Could not find Java executable
```

You can find my build in [my repo](https://github.com/BerkhanEminsoy/BerkhanEminsoy.github.io) either in the main branch (also my working branch) or the source branch (where my [github page](https://berkhaneminsoy.github.io/) gets built/deployed), but in my gem file I have; 

```
source 'https://rubygems.org'
gem 'jekyll', '~> 4.2'
gem 'jekyll-include-cache', group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'kramdown-parser-gfm' if ENV['JEKYLL_VERSION'] == '~> 3.9'
  gem 'asciidoctor-diagram', '~> 2.2', '>= 2.2.1'
  gem 'jekyll-asciidoc', github: 'asciidoctor/jekyll-asciidoc'
  gem 'minitest', '~> 5.14', '>= 5.14.4'
  gem 'rake', '~> 13.0', '>= 13.0.6'
  gem 'minima', '~> 2.5'
  gem 'jemoji', '~> 0.12.0'
  gem 'titleize', '~> 1.4', '>= 1.4.1'
  gem 'jekyll-remote-theme', '~> 0.4.3'
  gem 'jekyll-timeago', '~> 0.13.1'
  gem 'jekyll-feed', '~> 0.12'
  gem 'jekyll-sitemap', '~>1.4'
  gem 'jekyll-archives', '~> 2.2', '>= 2.2.1'
  gem 'jekyll-scholar', '~> 7.0'
  gem 'jekyll-webp', '~> 1.0'
  gem 'jekyll-loading-lazy', '~> 0.1.1'
  gem 'jekyll_figure', '~> 0.0.3'
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '~> 1.2'
  gem 'tzinfo-data'
end

gem 'wdm', '~> 0.1.1', :platforms => [:mingw, :x64_mingw, :mswin]
gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'
```

and my config is as follows; 

```
############################################################
# Plugins (previously gems)
plugins:
 - asciidoctor-diagram
 - jekyll-asciidoc
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-include-cache
 - jekyll-archives
 - jekyll/scholar
 - jekyll-webp
 - jekyll-loading-lazy
 - jekyll_figure
 - jemoji
 - titleize

############################################################
# Site configuration for the Jekyll-AsciiDoc Plugin
keep_files:
  - images

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: assets/img/ascii
    stem: ''
    :page-layout: auto@

```
 
I'll also add the steps I've taken to address the problem in no particular order;
  - installed graphviz-2.50.0 (64-bit) from [the graphviz.org website](http://www.graphviz.org/download/) w/ graphviz PATH added to all users
  - manually added `C:\Program Files\Graphviz\bin` dir to the windows 10 environment paths and placed it above the `ruby27-x64` PATH.
  - checked-out issue #142 and tried [this](https://github.com/asciidoctor/jekyll-asciidoc/issues/142#issuecomment-340991202)
  - followed the instructions on [How to configure Asciidoctor Diagram in a Jekyll site gist](https://gist.github.com/mojavelinux/968623c493190dd61c059c2d85f9bdc3)

Any help is much appreciated!
