### ISSUE TITLE
Path parameterization in _config.yaml

### ISSUE THREAD

**Issue by nfrankel** [asciidoctor/jekyll-asciidoc#279]
I'm faced with an issue. I'd like that images for every post should be stored under a parent folder + the path slug. I've tried the following to no avail:

```yaml
asciidoctor:
  attributes:
    imagesdir: /assets/resources/{page.outputpath}@
```

I've tried with and without the trailing `@` (to override it). I've tried with and without the `page` prefix.

I wonder if it's possible.
