### ISSUE TITLE
icons=fonts attribute

### ISSUE THREAD

**Issue by wbzyl** [asciidoctor/jekyll-asciidoc#32]
This is  my jekyll *_config.yml* file:

```yaml
asciidoctor:
  attributes:
    - icons=fonts
```
But generated HTML files contain this:

```html
<img alt="1" src="./images/icons/callouts/1.png"></img>
```

instead of this:

```html
<i class="conum" data-value="1">
```
