### ISSUE TITLE
Restructure configuration keys

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/jekyll-asciidoc#82]
Right now, all the general settings for the plugin are defined as top-level configuration keys.

* asciidoc
* asciidoc_ext
* asciidoc_page_attribute_prefix
* asciidoc_require_front_matter_header

I think these keys should be moved underneath the asciidoc key as follows:

```yaml
asciidoc:
  processor: asciidoctor
  ext: asciidoc, adoc, ad
  page_attribute_prefix: page
  require_front_matter_header: true
```

We can still support the old keys for backwards compatibility. We simply check if the asciidoc key has a String or Hash value. If the key has a String value, assume the old keys (issuing a warning and coercing them into the new structure). If it has a Hash value, use the new structure.

We'll leave the asciidoctor key alone as that's an orthogonal set of configuration.
